extends Node
#Global Enum

const NONE = "NONE"

const ROAD_NOMAL = "NOMAL"
const ROAD_RUINS = "RUINS"
const ROAD_WILDERNESS = "WILDERNESS"
const ROAD_WATER = "WATER"


const BUILDING_BASE = "BASE"
const BUILDING_HQ = "HQ"
const BUILDING_POWER_PLANT = "POWER_PLANT"
const BUILDING_DATA_STATION = "DATA_STATION"
const BUILDING_LIBRARY = "LIBRARY"
const BUILDING_SPECIAL = "SPECIAL"

const TYPE_NONE = "NONE"
const TYPE_DETECT = "DETECT"
const TYPE_CONTAINMENT = "CONTAINMENT"
const TYPE_ERADICATION = "ERADICATION"
const TYPE_SUPPORT = "SUPPORT"

const TAG_QUICK = "QUICK"
const TAG_SINK = "SINK"
const TAG_FORWARD_CHARGE = "FORWARD_CHARGE"
const TAG_NO_RETURN = "NO_RETURN"
const TAG_ENABLE = "ENABLE"
const TAG_HUMAN = "HUMAN"
const TAG_MONSTER = "MONSTER"
const TAG_MATERIAL = "MATERIAL"
const TAG_MACHINE = "MACHINE"
const TAG_PROJECT = "PROJECT"

const L1_START = "l1_start"
const L1_ORIGIN = "l1_origin"
const L1_LIBRARY = "l1_library"
const L1_STATION = "l1_station"
